import { z } from "zod";
import { PollRuleError } from "./errors";

export const AVATAR_TINTS = ["f8c9b9", "cbe2d8", "f6e0a4", "e3d2f2"] as const;

export const LIMITS = {
  titleLength: 120,
  optionLength: 80,
  nameLength: 40,
  minOptions: 2,
  maxOptions: 10,
  /** Creator options plus approved and pending suggestions. */
  maxBallotOptions: 20,
} as const;

const trimmed = (max: number) => z.string().trim().min(1).max(max);

export const avatarInput = z.object({
  seed: trimmed(64),
  tint: z.enum(AVATAR_TINTS),
});

export const personInput = z.object({
  name: trimmed(LIMITS.nameLength),
  avatar: avatarInput,
});

/** Opaque per-browser token; long enough that it can't be guessed. */
export const voterTokenInput = z.string().min(16).max(128);

export const createPollInput = z
  .object({
    title: trimmed(LIMITS.titleLength),
    options: z.array(trimmed(LIMITS.optionLength)).min(LIMITS.minOptions).max(LIMITS.maxOptions),
    closesAt: z.coerce.date(),
    voteType: z.enum(["single", "multi"]),
    maxChoices: z.number().int().min(1).default(1),
    suggestionsEnabled: z.boolean(),
  })
  .transform((input) => ({
    ...input,
    // A single-vote poll always allows exactly one choice, whatever was sent.
    maxChoices: input.voteType === "single" ? 1 : input.maxChoices,
  }));

export const castBallotInput = z.object({
  /** Generated by the client once per ballot, so a retried submit is recognisably the same ballot. */
  ballotId: z.uuid(),
  voterToken: voterTokenInput,
  voter: personInput,
  optionIds: z.array(z.uuid()).min(1).max(LIMITS.maxBallotOptions),
});

export const suggestOptionInput = z.object({
  label: trimmed(LIMITS.optionLength),
  suggestedBy: personInput,
  /** Identifies the suggesting browser for the per-voter cap; supplied by the API from the cookie. */
  voterToken: voterTokenInput,
});

export type CreatePollInput = z.input<typeof createPollInput>;
export type CastBallotInput = z.input<typeof castBallotInput>;
export type SuggestOptionInput = z.input<typeof suggestOptionInput>;

/** Parses untrusted input, turning validation failures into a rule error. */
export function parseInput<T extends z.ZodType>(schema: T, input: unknown): z.output<T> {
  const parsed = schema.safeParse(input);
  if (!parsed.success) {
    throw new PollRuleError("INVALID_INPUT", z.prettifyError(parsed.error));
  }
  return parsed.data;
}
