import { sql } from "drizzle-orm";
import {
  boolean,
  check,
  index,
  integer,
  pgEnum,
  pgTable,
  primaryKey,
  text,
  timestamp,
  unique,
  uuid,
} from "drizzle-orm/pg-core";

export const voteType = pgEnum("vote_type", ["single", "multi"]);
export const pollStatus = pgEnum("poll_status", ["open", "settled"]);
export const optionSource = pgEnum("option_source", ["creator", "suggestion"]);
export const suggestionStatus = pgEnum("suggestion_status", ["pending", "approved", "declined"]);

const timestamps = {
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
};

export const polls = pgTable(
  "polls",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    /** Unguessable in real polls: the link is the access control for voting. */
    slug: text("slug").notNull().unique(),
    // Becomes a foreign key to the auth user table once creator accounts land (scope 2).
    creatorId: text("creator_id").notNull(),
    title: text("title").notNull(),
    voteType: voteType("vote_type").notNull().default("single"),
    maxChoices: integer("max_choices").notNull().default(1),
    suggestionsEnabled: boolean("suggestions_enabled").notNull().default(true),
    status: pollStatus("status").notNull().default("open"),
    closesAt: timestamp("closes_at", { withTimezone: true }).notNull(),
    settledAt: timestamp("settled_at", { withTimezone: true }),
    ...timestamps,
  },
  (table) => [
    index("polls_creator_idx").on(table.creatorId),
    check("polls_max_choices_check", sql`${table.maxChoices} >= 1`),
  ],
);

/** Creator options and voter suggestions live together: approval is a status flip. */
export const options = pgTable(
  "options",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    pollId: uuid("poll_id")
      .notNull()
      .references(() => polls.id, { onDelete: "cascade" }),
    label: text("label").notNull(),
    position: integer("position").notNull(),
    source: optionSource("source").notNull().default("creator"),
    suggestionStatus: suggestionStatus("suggestion_status"),
    suggestedByName: text("suggested_by_name"),
    suggestedByAvatarSeed: text("suggested_by_avatar_seed"),
    suggestedByAvatarTint: text("suggested_by_avatar_tint"),
    ...timestamps,
  },
  (table) => [
    index("options_poll_idx").on(table.pollId),
    check(
      "options_suggestion_fields_check",
      sql`(${table.source} = 'creator' AND ${table.suggestionStatus} IS NULL)
        OR (${table.source} = 'suggestion' AND ${table.suggestionStatus} IS NOT NULL AND ${table.suggestedByName} IS NOT NULL)`,
    ),
  ],
);

/**
 * One row per voter per poll. The unique (poll, voter token) pair is what makes
 * "one ballot per browser" a database guarantee, including pick-up-to-N polls
 * where a ballot has several votes. The id is generated by the client so a
 * retried submission is recognisably the same ballot.
 */
export const ballots = pgTable(
  "ballots",
  {
    id: uuid("id").primaryKey(),
    pollId: uuid("poll_id")
      .notNull()
      .references(() => polls.id, { onDelete: "cascade" }),
    voterToken: text("voter_token").notNull(),
    voterName: text("voter_name").notNull(),
    avatarSeed: text("avatar_seed").notNull(),
    avatarTint: text("avatar_tint").notNull(),
    castAt: timestamp("cast_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [unique("ballots_poll_voter_unique").on(table.pollId, table.voterToken)],
);

export const votes = pgTable(
  "votes",
  {
    ballotId: uuid("ballot_id")
      .notNull()
      .references(() => ballots.id, { onDelete: "cascade" }),
    optionId: uuid("option_id")
      .notNull()
      .references(() => options.id, { onDelete: "cascade" }),
  },
  (table) => [primaryKey({ columns: [table.ballotId, table.optionId] }), index("votes_option_idx").on(table.optionId)],
);
